name: Nuget Package Deploy

on: 
 push:
   branches: 
     - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'
    - uses: actions/checkout@v3.5.3  
    - name: Setup NuGet.exe 
      uses: NuGet/setup-nuget@v1.1.1 
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Nuget Restore
      run:  nuget restore SamsungAccessorySDK-Maui\SamsungAccessorySDK-Maui.csproj
    - name: Build with dotnet
      run: msbuild SamsungAccessorySDK-Maui\SamsungAccessorySDK-Maui.csproj -property:Configuration=Release
    - name: Push Package to nuget
      run: dotnet nuget push **/*.nupkg
             --api-key ${{ secrets.nugetapikey }}
             --source https://api.nuget.org/v3/index.json
