name: Nuget Package Deploy

on: 
 push:
   branches: 
     - master
   paths:
    - 'SamsungAccessorySDK.nuspec'
    - 'SamsungAccessorySDK\SamsungAccessorySDK.csproj'
jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'
    - uses: actions/checkout@v2     
    - name: Setup NuGet.exe 
      uses: NuGet/setup-nuget@v2.0.0  
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Build with dotnet
      run: msbuild SamsungAccessorySDK\SamsungAccessorySDK.csproj -property:Configuration=Release
    - name: Nuget Pack
      run:  nuget pack SamsungAccessorySDK.nuspec
    - name: Push Package to nuget
      run: dotnet nuget push **/*.nupkg
             --api-key ${{ secrets.nugetapikey }}
             --source https://api.nuget.org/v3/index.json
