name: Nuget Package Deploy

on: 
 push:
   branches: 
     - master
jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2     
    - name: Setup NuGet.exe 
      uses: NuGet/setup-nuget@v1.0.5    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Build with dotnet
      run: msbuild SamsungAccessorySDK-Maui\SamsungAccessorySDK-Maui.csproj -property:Configuration=Release
    - name: Nuget Pack
      run:  nuget pack SamsungAccessorySDK-maui.nuspec
    - name: Push Package to nuget
      run: dotnet nuget push **/*.nupkg
             --api-key ${{ secrets.nugetapikey }}
             --source https://api.nuget.org/v3/index.json
